version: "2.2"
services:
  activemq:
    build: .
    image: corban-activemq
    container_name: Corban_ActiveMQ_Container
    ports:
      - "61616:61616"
      - "8161:8161"
      - "9009:9009"
      - "61613:61613"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
      - /home/ubuntu/Jebin/Corban_Project_Docker_21_06_2022/Corban_Activemq/activemq_data/:/var/lib/activemq
    restart: always
    mem_limit: 2000m
    mem_reservation: 200m
    cpus: 1.5
networks:
  default:
    external:
      name: my-shared-network